### ISSUE TITLE
Blender3.5での動作について

### ISSUE THREAD

**Issue by Bancho29** [bookyakuno/Blender-Scramble-Addon#20]
本日（2023年3月30日）、Blender 3.5がリリースされましたが、
Blender-Scramble-Addonが実行された形跡がないばかりか、
削除後に再インストール→再有効化しようとしたときに、
画像のようなエラーが出てきました。
![scr_err](https://user-images.githubusercontent.com/19154759/228784945-8515ea5b-0643-4975-93f0-4a7c6a15d9f5.png)
（ちなみに、旧バージョンの設定を移行しない、まっさらな設定でも起きました。）

3.4及び3.3では発生しませんでした。

2021年2月14日のver1.1.0以降更新がなく、3.xへの正式対応が無いままでしたが、
そのままサポート終了になるでしょうか？

**Comment by bookyakuno** [comment]
問題を修正したver1.1.1を公開しました。
https://github.com/bookyakuno/Blender-Scramble-Addon/releases/tag/v1.1.1

・Blender3.5にて、アドオンの有効化に失敗する問題を修正しました。
(Blender3.5にて、ポーズライブラリが廃止されたことが原因でした)

正直このアドオンはもう自身が使用しておらず開発モチベーションは低いので、
追加機能のような更新は期待しないでください。
気が向いた時にバグ修正程度はするかもです。

**Comment by Bancho29** [comment]
修正ありがとうございます。

しかし、先程ver1.1.1をインストールしましたが、画像のようなエラーが出てきました。

![スクリーンショット (151)](https://user-images.githubusercontent.com/19154759/229074658-784d4204-8e6d-44bc-a1e2-a50e0628c0e2.png)

上：Blender Launcherでダウンロードしたzip版
下：Steam版
メッセージからしてモジュールが不足している模様です。

> 正直このアドオンはもう自身が使用しておらず開発モチベーションは低いので、
> 追加機能のような更新は期待しないでください。
> 気が向いた時にバグ修正程度はするかもです。> 

了解しました。

**Comment by bookyakuno** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\blender350\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Blender-Scramble-Addon-1'
```

これは、アドオンのフォルダ名に" . "が入ってしまっていることが原因でインストールできない、という問題でした。
Releaseで公開しているzipの展開後のフォルダ名を、バージョン名が入らない"Blender-Scramble-Addon"に変更しました。

既存のアドオンフォルダでも、フォルダ名を変更すればインストールできるはずです。

**Comment by Bancho29** [comment]
> Releaseで公開しているzipの展開後のフォルダ名を、バージョン名が入らない"Blender-Scramble-Addon"に変更しました。

こちらをダウンロードしたら、無事インストールできました。
ご手数かけて申し訳ありませんでした。
