### ISSUE TITLE
Blender 3.6 support

### ISSUE THREAD

**Issue by Wolfgang-IX** [bookyakuno/Blender-Scramble-Addon#21]
Hi i've the same problem as this when installing it on Blender 3.6.2 [20](https://github.com/bookyakuno/Blender-Scramble-Addon/issues/20)

on Blender 3.5.1 works fine

here's the errors
![image](https://github.com/bookyakuno/Blender-Scramble-Addon/assets/47208316/9b9c3700-9e9b-49ba-9fea-45cb011dac1a)

**Comment by Andrej730** [comment]
@Wolfgang-IX tested on 3.6.3, it's installing fine.

Looking at the second error - it seems you have some other addon overriding `DATA_PT_shape_keys`, try to disable addons and try again. You can start blender with `--factory-startup` to make sure no other addons enabled and test it.

The first error is just a consequences of trying to enable the addon again after you already got the second error, so there is no issue.

**Comment by Wolfgang-IX** [comment]
thanks it's working now, conflict with [Shape Keys+](https://github.com/MichaelGlenMontague/shape_keys_plus). 
need to enable scramble first then that
