### ISSUE TITLE
name

### ISSUE THREAD

**Issue by hgq123** [bookyakuno/Blender-Scramble-Addon#5]
File ":blender zxblender 2.82a windows64\2.82lscriptsmodulesladdon utils,py", line 351, in enable mod= import_ (module. name)
ModuleNotFoundError No rmodule named 'Blender-Scramble-Addon-1'

**Comment by bookyakuno** [comment]
The error is "Cannot install if the file name contains ".".
Example → "Blender-Scramble-Addon-v1.0.2"

The zip file on the Release page has been renamed so it should be improved.


「ファイル名に" . " が含まれているとインストールできない」というエラーです。
例 →  "Blender-Scramble-Addon-v1.0.2"

Releaseページのzipファイルの名前を変更しましたので、改善されたはずです。
